# Generated by Django 6.0.7 on 2026-07-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_review_updated_at_alter_review_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
