# Generated by Django 6.0.7 on 2026-07-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_remove_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
