# Generated by Django 6.0.7 on 2026-07-19 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='salon.appointment'),
        ),
    ]
