# Generated by Django 6.0.7 on 2026-07-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='icon',
            field=models.CharField(default='📁', max_length=10),
        ),
    ]
